# Generated by Django 4.2.11 on 2026-04-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="out",
            field=models.BooleanField(default=False),
        ),
    ]
